### ISSUE TITLE
Install instructions are broken

### ISSUE THREAD

**Issue by QuLogic** [codeauroraforum/lid#1]
It says to do:
```
pip install --process-dependency-links git+https://github.qualcomm.com/qosp/lid.git
```
but a) `--process-dependency-links` is not accepted by pip and b) github.qualcomm.com is not available.

**Comment by craigez** [comment]
The URL is leftover from before this was released as open source. It should be: git+https://github.com/codeauroraforum/lid.

"--process-dependency-links" may have been deprecated in recent versions of pip. I'll need to look at what the correct replacement is.

Thanks for pointing this out.

**Comment by craigez** [comment]
The need for dependency links option was removed in 8160429ab6ff224435ee716ccf7b8094df770c1d.
